# version: '3'

# services:
#   app:
#     build: 
#       context: .
#       dockerfile: docker/php/Dockerfile
#     image: "eatwell_app"
#     depends_on:
#       -db
#     volumes:
#       - .:/projects:rw
#       - app-var:/projects/var:rw
#       - ./vendor:/projects/vendor:cached
#       - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#       - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

#   www:
#     build:
#       context: .
#       dockerfile: docker/nginx/Dockerfile
#     image: eatwell/nginx
#     container_name: "eatwell_www"
#     volumes:
#       - ./web:/projects/web:ro
#     ports:
#       - "80:80"

#   db:
#     build:
#       context: docker/database
#     environment:
#       MYSQL_USER: eatwell
#       MYSQL_PASSWORD: eatwell
#       MYSQL_DATABASE: eatwell_dev
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - ./dev/sql/initial-server-data.sql:/docker-entrypoint-initdb.d/initial-prod-data-and-schema.sql
#       - db_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
